# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('happening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 1, 4, 32, 33, 322541, tzinfo=utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 1, 4, 32, 41, 528922, tzinfo=utc), verbose_name='Last Updated On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.SlugField(default='genny', unique=True, verbose_name='Url: www.isdndhappeningthisweek.com/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='dow',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='Day of Week'),
        ),
        migrations.AlterField(
            model_name='game',
            name='happening',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is it happening this week?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
